### ISSUE TITLE
Using the API - decode returning "junk" characters in addition to private message

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#1]
Hi - I'm testing Steganographer's API, and finding that the response I'm getting back, when I "view source" on the GET /api?decode= result page, is actually not 100% like the original private message, instead having some "junk" characters. Please see the screenshot. 

<img width="754" alt="image" src="https://user-images.githubusercontent.com/512328/95545839-eff29c00-0a39-11eb-84fc-35b3955aafb3.png">

Is there a way that the decode function could return the original private message and only the original private message by any chance? 

Sincerely,
Rick

**Comment by newbold** [comment]
Hi Rick, thanks for the report. You've probably put the API through its paces far more than I have at this point. 😄  Turns out those junk characters were an artifact of the binary conversion function. When viewing the source in Safari they don't show up at all, in Chrome they show up as red dots, and in Firefox they show up with the character icon in your screenshot. Since I only lazily tested this in Safari, I never caught it (shame on me). But the good news is that thanks to you I found the underlying issue and fixed it! Let me know if you run into any other issues with it.

**Comment by RickCogley** [comment]
Much appreciated and I confirm I'm finding no more binary "lint" in the returned data. Nice!

**Comment by RickCogley** [comment]
By the way @newbold, would you be amenable to releasing the api code or, is that something you don't want to do? I'm happy to donate, because I'd like to run this internally.

**Comment by newbold** [comment]
No problem! [Here's the API source](https://raw.githubusercontent.com/neatnik/steganographr/master/steganographr-api.php) (which has also been added to the repo).

**Comment by RickCogley** [comment]
thanks very much!

**Comment by RickCogley** [comment]
Just curious about how you set this up on your server. You explain on the api page to do a GET like this: 

> GET https://neatnik.net/steganographr/api?public=It+sure+is+hot+today&private=meet+me+behind+the+office+at+4+pm

The url path is `/api?param=` so, does that mean you just store the `steganographer-api.php` file as just `api` with no extension in the root of your server? Or, did you put the `steganographer-api.php` as `index.php` under an `/api` folder?

**Comment by newbold** [comment]
Yep, the folder approach you mentioned is pretty much what I'm doing. I actually have `steganographer-api.php` inside the `/api` folder, with a `.htaccess` file containing `DirectoryIndex steganographr-api.php`. But if you don't care about the filename, simply storing it as `index.php` is easier and works too.

**Comment by RickCogley** [comment]
Right, that makes sense too. Makes it easier to deal with if that's what you have in the repo. 

I have nginx, so doing this would need a `try_files` directive in the nginx conf, to make the equivalent of `DirectoryIndex` in an `.htaccess` file. But I'll just be lazy and rename it as `/api/index.php` if I need ppl to see the message. It's working fine as `api.php` from my test script.
