### ISSUE TITLE
Imp

### ISSUE THREAD

**Issue by Soham040** [neatnik/steganographr#10]
Hello there, I tried your code it seems it doesn't work well on the mobile browser.
Basically, it encodes the text but while decoding it doesn't decode well, after trying 2-3 times continuously it works.
Do you have any solution to this?

**Comment by newbold** [comment]
Hi @Soham040, can you let me know what OS and browser you're using? I have only tested on iOS using mobile Safari and Chrome, and both work for me without any issue.

**Comment by Soham040** [comment]
> Hi @Soham040, can you let me know what OS and browser you're using? I have only tested on iOS using mobile Safari and Chrome, and both work for me without any issue.

@newbold  The code and your website work very well on my windows 11 but don't on mobile

**Comment by newbold** [comment]
Hmm, this is a tough one. The code is 100% back-end stuff, so it's browser agnostic. There’s no JS or anything that could be interfering on the front-end. The markup is standard, semantic, and valid. It’s really puzzling why it wouldn’t work with a specific mobile browser — but what makes it worse is that there’s no easy way to troubleshoot. I'm going to see if I can connect with some other folks who are running Android devices so I can try to collect some more data, and I’ll let you know what I learn.

**Comment by newbold** [comment]
That would be helpful! It might yield a clue or two as to what's going on. I appreciate it!

**Comment by Soham040** [comment]
@newbold 
Here's the video 👇😁
https://user-images.githubusercontent.com/105621250/168829340-9b265502-581e-427c-8208-ab0f38db7587.mp4

**Comment by newbold** [comment]
Thanks for sharing that. It’s a mystery! Someone else has tested on an Android device using Chrome, Brave, and Firefox without any issue. Is there any chance that you have some kind of extension that could possibly be affecting the site’s behavior? Are you able to test in a different browser, like Firefox?

**Comment by newbold** [comment]
Ah, new info — someone let me know that it looks like you're pasting with the keyboard, and not with the system paste. The keyboard paste is probably filtering out the stuff that makes Steganographr work, but if you use the system paste it should work!

**Comment by Soham040** [comment]
@newbold woh

> Ah, new info — someone let me know that it looks like you're pasting with the keyboard, and not with the system paste. The keyboard paste is probably filtering out the stuff that makes Steganographr work, but if you use the system paste it should work!

@newbold  Woh! that might be the issue. I tried it using system paste and it worked 😴😊 !! 
Thanks for resolving my problem.

**Comment by Soham040** [comment]
> 

@newbold  I never imagined about that😱

**Comment by newbold** [comment]
Glad it worked out! And I learned something new about Android today. 😁
