### ISSUE TITLE
Testing on own php 7.4 server, getting "invalid characters" errors

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#2]
Hi - I did a very simple clone of this repo, and copy the main file steganographer.php as index.php on a php 7.4 nginx server to test. It basically works (haven't added any styles yet), but I'm getting an error inline: 

```
Deprecated: Invalid characters passed for attempted conversion, these have been ignored in /home/stegesoliapro/steg.esolia.pro/index.php on line 57
```

Looks like this is in the `bin2str` function, which uses php's `bindec` lib function. The manual <https://www.php.net/manual/en/function.bindec.php> says that as of PHP 7.4:

>  Passing invalid characters will now generate a deprecation notice. The result will still be computed as if the invalid characters did not exist. 

So, is there any way to fix? 

<img width="1537" alt="image" src="https://user-images.githubusercontent.com/512328/95712137-33017900-0c9f-11eb-8182-b77b8362a78e.png">

**Comment by newbold** [comment]
Sorry about that! I do an embarrassing amount of development in a production environment that has various errors/notices suppressed, so I never even saw those messages. I've updated the code in the repo to properly prevent the deprecation notice. The underlying approach in Steganographr actually relies on the fact that `bindec()` ignores non-binary data (so this is working exactly as intended), but it's easy enough to prevent the unwanted output. 👍

**Comment by RickCogley** [comment]
Much appreciated! Confirmed the fix. 
Interesting that you can just prepend an `@` to the function name to suppress.
