### ISSUE TITLE
Works with Japanese, mostly

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#3]
It's cool that the steganographer API works with Japanese text and not just latin. It doesn't matter if the chars surrounding the zero-byte ones are CJK or not; it "just works". Nice! 

At first I wrote this issue just to say "it works" but, I did find a case that has a little bug. 

If you enter 3 or more double byte Japanese chars in the "public" string, everything is peachy: 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95805256-ea4dcc80-0d3f-11eb-9ed5-3646d8dc6746.png">

* * * 

However, if you enter _less_ than 3 double byte chars, it shows the first kanji char of the entered string and some junk ?-looking chars  `公�‌‌‌​​‌‌‌⁠‌​‌​​‌‌‌⁠‌​​‌‌​​​⁠‌‌‌​​‌​‌⁠‌​‌​‌‌‌‌⁠‌​​​​‌‌​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​‌​‌​⁠‌‌‌​​‌‌​⁠‌​​‌​‌‌​⁠‌​​​​‌‌‌⁠‌‌‌​​‌​‌⁠‌​‌​‌‌​‌⁠‌​​‌​‌‌‌⁠‌‌‌​​‌​‌⁠‌​​​‌​​​⁠‌​​‌​‌‌‌��` after you steganographize. 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95805442-62b48d80-0d40-11eb-8d51-a77f6b6a7285.png">

* * * 

If you copy the string with the junk and de-steganographize, that process works fine, though, and you get back what you expected. 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95805585-b7580880-0d40-11eb-8fca-9c1d9947be01.png">

* * * 

At first I thought this artefact might be coming from the English lang specifier in the `<html>` tag, but, even after changing to `<html lang="ja">`, it makes no difference.

**Comment by newbold** [comment]
Thanks! I always try to make things that are Unicode-friendly, though it doesn't always go as planned. 😄

**Comment by RickCogley** [comment]
> Thanks! I always try to make things that are Unicode-friendly, though it doesn't always go as planned. 😄

I spoke too soon and found an oddness, then edited the above with some screenshots. Not sure what can be done about it. It's because I was listlessly testing using a really short 2-kanji string in the public text area that I found it!

**Comment by RickCogley** [comment]
By the way when you use a single English byte for the public message, it displays an error, but, even this too still works for de-steganographication (de-s17n, lol!). 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95806133-f3d83400-0d41-11eb-8962-b5ae77f34e32.png">

**Comment by newbold** [comment]
Oooh, good catch. And, actually, both issues (the garbage characters _and_ the single-byte public messages) are related. I took the string これはテストです (courtesy of Google Translate, heh) as a public message and saw that it didn't work. I started removing one character at a time to see what would happen, and that's when I saw it: これはテストで worked fine, これはテスト failed, これはテス worked fine, etc., in that alternating pattern. Then as soon as you shared the single byte issue, it clicked.

Here's what's happening. In order to hide the "hidden" binary data inside of the string, Steganographr splits the string in half and then stores the invisible characters between the visible ones. This ensures that when you copy the "steganographized" message, the hidden stuff is included. If I prepended it to the string or appended it to the end, there'd be a risk that it wouldn't get picked up when selecting the text and copying.

So: a single-byte character triggers that error because there's nothing to split in half. I think the reason it still worked for you is when you selected the string you still picked up the hidden stuff somehow, though it could just as easily have failed. I think you just got lucky. 😁 In the case of multibyte unicode characters, the approach that I'm using to split the string in half is obviously not multibyte-friendly.

This should be a fairly easy fix, I think. Will try to knock it out shortly and report back. 👍

**Comment by RickCogley** [comment]
Ah right. I confirm reducing the Japanese string by a double byte at a time, gives alternating success and failure. Interesting. 

> I think the reason it still worked for you is when you selected the string you still picked up the hidden stuff somehow, though it could just as easily have failed. 

I always triple-click to select such things, so that might be why it picked it up.

**Comment by newbold** [comment]
Should be good to go now! Code in the repo has been updated. Thanks for catching this, and don't hesitate to let me know if you notice any other issues.

**Comment by RickCogley** [comment]
Thank you! This fixes the problem of those "junk" characters appearing or not appearing as you remove bytes. 

However, there's still a small problem with one-kanji public messages. Given any one-char Kanji (tried 5 or so, not all bazillion of them) as the public message, and some arbitrary kanji text as the secret, after you steganographize, it presents the Kanji in the encoded text box, but when you copy that out and try to de-steganographize, it gives the error "no private message was found". FYI: 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95809515-f5a5f580-0d49-11eb-8a9e-6461900b1a67.png">

**Comment by newbold** [comment]
Ah, yeah, another good catch -- this was the result of the new multibyte-friendly setup. Repo code updated! Now, single character inputs (regardless of the number of bytes) will have the hidden payload appended to the end, and the triple-clicking selection should pick everything up. As always, let me know if you run into any other issues. Hopefully I got it this time. 😄

**Comment by RickCogley** [comment]
Thanks! Getting closer; it does work now for single byte kanji, but, there's an error that appears no matter how many chars you enter. (Sorry to be so annoying)

>  Warning: count(): Parameter must be an array or an object that implements Countable in /home/stegesoliapro/steg.esolia.pro/index.php on line 155

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95811363-18d2a400-0d4e-11eb-882d-7c760b65c164.png">

**Comment by RickCogley** [comment]
And, when you enter English now, it returns just a single byte as the steganographized message. Copying that single byte and de-steganographizing it does result in the correct private message FYI.

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95811614-9f878100-0d4e-11eb-9a71-02bbc4416aab.png">

**Comment by newbold** [comment]
Yikes, sorry, it's all silliness on my end. I still don't have a proper development environment set up, so I keep missing simple error messages (and other related goofiness).

I think I've got it this time, though, and the repo code has been updated. I've also created a set of regression tests to help keep things sane, and just ran them through the new code prior to committing:

### Roman character input, multiple words
Public: `This is a public message.`
Private: `This is a private message.`
Stegnographized: This is a pub‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​lic message.
Destegnosgraphized: `This is a private message.`
Result: ✅ Passed

### Roman character input, single character
Public: `z`
Private: `This is a private message.`
Stegnographized: z‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​
Destegnosgraphized: `This is a private message.`
Result: ✅ Passed

### Japanese character input, multiple characters
Public: `これは公開メッセージです。`
Private: `これはプライベートメッセージです。`
Stegnographized: これは公開メッ‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​​​‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​‌‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌​​‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​​​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​​​⁠‌​​​​​‌​セージです。
Destegnosgraphized: `これはプライベートメッセージです。`
Result: ✅ Passed

### Japanese character input, single character
Public: `水`
Private: `これはプライベートメッセージです。`
Stegnographized: 水‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​​​‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​‌‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌​​‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​​​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​​​⁠‌​​​​​‌​
Destegnosgraphized: `これはプライベートメッセージです。`
Result: ✅ Passed

Hopefully this covers everything! But I do want this to be perfect, so really, please don't hesitate to let me know if you catch any new issues at all. 👍

**Comment by RickCogley** [comment]
Quick tests show, it's working! Thanks!

**Comment by RickCogley** [comment]
I did see the "your public message must be at least 2 characters" error. I know I can live with that constraint, and I cannot see why anyone else could not either, imo.
