### ISSUE TITLE
Some public strings not working for encoding

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#5]
Hi - not sure what this is about. I tried using a guid string like 1a73a4ce2669411f875fcbbccaf60928 as the public message, the encoding does not seem to work. If I enter another 32 char string like asdfqwerasdfqwerasdfqwerasdfqwer, it seems to work. 

I observe that the encoded string gets what appears to be a newline, at least visually, so that might be having some impact... 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/512328/95838881-46831180-0d7d-11eb-869c-8b3c80e075a0.png">

**Comment by RickCogley** [comment]
Tried a 32 char string with spaces "the the the the the the the the " and it works fine FYI.

**Comment by newbold** [comment]
OK, the latest code in the repo should fully address the issue of binary character conflict. It works by introducing a new wrapper around the hidden binary data (using another hidden character, heh), which makes identifying the hidden text more precise.

While the encoding process has changed slightly, I've preserved backwards compatibility with the previous process. If you have existing stored steganographrized strings, they should decode just fine in this new version.

I've added a couple of new regression tests -- one to verify the backwards compatibility, and another to address the original issue that you raised here (the binary format conflict when decoding).

Let me know if you notice any other issues! Thanks for putting this through its paces and helping to make it a better product. 👍 

### Regression tests against commit 3d883a9

#### Steganographrized message from prior version (/old)
Public: `This is a public message.`
Private: `This is a private message.`
Steganographrized: This is a pub‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​lic message.
Desteganographrized: This is a private message.
Result: **Passed** ✅

#### Conflicting binary characters in public message
Public: `01`
Private: `This is a private message.`
Steganographrized: 0﻿‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​﻿1
Desteganographrized: `This is a private message.`
Result: **Passed** ✅

#### Roman character input, multiple words
Public: `This is a public message.`
Private: `This is a private message.`
Steganographrized: This is a pub‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​lic message.
Desteganographrized: `This is a private message.`
Result: **Passed** ✅

#### Roman character input, single character
Public: `z`
Private: `This is a private message.`
Steganographrized: z‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​‌​‌​‌​​⁠‌‌​‌​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​‌​​‌⁠‌‌‌​​‌‌⁠‌​​​​​⁠‌‌​​​​‌⁠‌​​​​​⁠‌‌‌​​​​⁠‌‌‌​​‌​⁠‌‌​‌​​‌⁠‌‌‌​‌‌​⁠‌‌​​​​‌⁠‌‌‌​‌​​⁠‌‌​​‌​‌⁠‌​​​​​⁠‌‌​‌‌​‌⁠‌‌​​‌​‌⁠‌‌‌​​‌‌⁠‌‌‌​​‌‌⁠‌‌​​​​‌⁠‌‌​​‌‌‌⁠‌‌​​‌​‌⁠‌​‌‌‌​
Desteganographrized: `This is a private message.`
Result: **Passed** ✅

#### Japanese character input, multiple characters
Public: `これは公開メッセージです。`
Private: `これはプライベートメッセージです。`
Steganographrized: これは公開メッ‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​​​‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​‌‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌​​‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​​​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​​​⁠‌​​​​​‌​セージです。
Desteganographrized: `これはプライベートメッセージです。`
Result: **Passed** ✅

#### Japanese character input, single character
Public: `水`
Private: `これはプライベートメッセージです。`
Steganographrized: 水‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​​​‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​‌‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌​​‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌​​​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​​​​​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​‌‌⁠‌​‌‌‌‌​​⁠‌‌‌​​​‌‌⁠‌​​​​​‌​⁠‌​‌‌‌​​​⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​‌​​‌‌‌⁠‌‌‌​​​‌‌⁠‌​​​​​​‌⁠‌​​‌‌​​‌⁠‌‌‌​​​‌‌⁠‌​​​​​​​⁠‌​​​​​‌​
Desteganographrized: `これはプライベートメッセージです。`
Result: **Passed** ✅

**Comment by RickCogley** [comment]
Thanks for the fix! I'll load it up later and test. 

So, can we say that if the public string is a long text block like a guid, manual decoding might fail due to browser wrap behavior, but API decoding should be ok?

**Comment by newbold** [comment]
In theory, browser wrap behavior _shouldn't_ cause anything to fail unless the end user doing the copying fails to include the full text in their selection. The wrapping doesn't actually alter the text, though in theory it creates a condition that could cause user error in the selection. But as long as you do a "select all" or triple-click (as you mentioned), it shouldn't be an issue. And yeah, the API should generally be fine as well.

**Comment by RickCogley** [comment]
I can confirm it seems to be working fine now. I did various tests and I'm not seeing any errors.
