### ISSUE TITLE
FYI: API performance

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#7]
Just an FYI. I'm sure various factors impact this, but I ran a script to encode many entries in a db, and the API supported about 4 calls per second. Web server is nginx running php 7.4, on ubuntu linux, on a fairly resource limited VM. At any rate, I won't ever need to "bulk encode" like this, but it was interesting to see that it could zip through 700-odd encode calls in test.

**Comment by newbold** [comment]
Cool! I haven't done any true performance evaluation, but Steganographr isn't doing anything overly taxing and should run pretty swiftly. But you're right, there are quite a few variables that can come into play for operations per second. Was your script was performing the encoding and then immediately INSERTing into your database? I could easily see the core API performing more than 4 conversions per second (likely _many_ more) but database overhead play a large role in overall speed. Either way, though, whether you batch-encoded a bunch of stuff and then inserted it all separately afterward or do convert-and-insert, the total amount of time would be pretty consistent.

[Salty](https://github.com/neatnik/salty), on the other hand, is doing quite a bit more heavy lifting with respect to cryptographic functions—so batch operations would be comparatively slower with it over Steganographr.

**Comment by RickCogley** [comment]
The script is running via a UI layer on top of the db and yes, inserting for each encode op, so, there's overhead there as well that I forgot to mention. If I ran the script purely from the CLI on localhost, I think it would be faster. And yes, anything crypto always uses lots of CPU and RAM.
