### ISSUE TITLE
Ampersands in text to encodify

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#8]
Hi - we noticed something. When we send a string to have it encodified with `&private=`, we found that if the string has ampersands, and our database url-encodes those, they are encoded as `&amp;`. So if the string is sent as `abc&%&123`, our db is sending as `abc&amp;%&amp;123` which steganographr is dutifully encoding. 

Can you think of any strategy to avoid this, so that we get back what we intended? I am yet to try _not_ url-encoding the private string but will if you think that might work. Appreciate your help.

**Comment by newbold** [comment]
I [added something](https://github.com/neatnik/steganographr/commit/1e0c013063a10e54545356a6a6437ce7a6b31958) to the API code that might help (assuming that I understand the issue fully). If the decoded text to be sent back includes encoded ampersands, it'll convert those to the intended `&` character. Let me know if this helps! You can grab the updated script [here](https://raw.githubusercontent.com/neatnik/steganographr/master/steganographr-api.php), or you can text it live at https://neatnik.net/steganographr/api/.

**Comment by RickCogley** [comment]
thanks for the work on this @newbold 👍 

Ok, so I tested in your site (made sure to clear the cache first), doing a GET in the browser with your test string, replacing a character in the string with `&amp;`. I then copy the encoded string and pass it to decode, and what happens is, the returned decoded private string gets cut off at the ampersand.

In terms of process on our end: 

* user enters a private string with an ampersand
* user clicks encode button, and the db url-encodes the string and passes it to the steganographr api, so it's passing the `&amp;` in that step
* steg dutifully encodes the `&amp;` as is
* user clicks decode button, and steg dutifully decodes showing the `&amp;`

**Comment by newbold** [comment]
Yeah, my web server (Apache) will be tripped up by ampersands because it treats anything after an ampersand as a parameter in a query string (and not part of the string associated with the prior parameter). Even an encoded ampersand entity, like `&amp;`, would be affected by that in Apache—but Apache is totally happy with the decimal encoding process that turns an ampersand into `%26` (and that will slip right through in a query string and be treated as an actual ampersand character).

To clarify, when you're doing this on your end, are you running your own copy of the API script? If that's the case, can I ask what kind of web server you're running?

**Comment by RickCogley** [comment]
Hi - yeah, edited the above comment as it looks like I'm also passing `%26`, looking at the log; sorry for the misinformation. We are using our own copy of the API script, running on nginx.

**Comment by RickCogley** [comment]
Ok, did the same test on your site, replacing a letter with `%26` and it works as expected.

**Comment by newbold** [comment]
OK, gotcha. I've never used nginx so but thanks to your linked script above I could see how it works. Looks like it's identical behavior to Apache -- an unencoded ampersand is treated as a query string parameter delimiter, but encoded ones (as `%26`) are passed through as strings. So at this point is everything OK with the setup on your end, or did you need any other adjustments made? Glad to help if you still need something!

**Comment by RickCogley** [comment]
Ok, I'll test again. I think something was cached on my side. Not sure if this is related, but please see the screenshot. I'm seeing errors again at the top, and also the sample URL in the Encoding section looks borked. 

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/512328/99025042-3c864580-25ab-11eb-9297-01c1d3a49413.png">

**Comment by RickCogley** [comment]
As for it working or not, ok, got it working in my db. Thanks!
Still not 100% sure, but, it appears my db is doing an additional url encode on the string that comes back from steganographr. I did a quick regex on it and that fixes it for display purposes.

**Comment by newbold** [comment]
It looks like `REQUEST_SCHEME` might be an Apache-specific thing, so I removed it. It was purely cosmetic (used to decide whether to show HTTP or HTTPS in the API landing page URLs), and I just went ahead and replaced the reference with HTTPS until I figure out a more universal way to detect a TLS connection. 😄 Updated script is here: https://github.com/neatnik/steganographr/blob/master/steganographr-api.php
