### ISSUE TITLE
Impact ?

### ISSUE THREAD

**Issue by RickCogley** [neatnik/steganographr#9]
Hi, Happy new year! I saw this commit which looks extensive. What's the impact of this change?

https://github.com/neatnik/steganographr/commit/7ab5bb2b21c5561eba281bb29d83cc17e3af0457

**Comment by newbold** [comment]
Ah, sorry, didn't mean to introduce any confusion. There are no functional changes at all—turns out by mistake I committed a modified version meant to integrate with my website's new content framework. Didn't mean to do that! I'll fix it now.

**Comment by RickCogley** [comment]
Hi, thanks. I was just wondering if I need to test a new release :-)
